import { useEffect, useState } from "react";
import { useLocation } from "react-router-dom";
import DashboardLayout from "../components/DashboardLayout";
import Icon from "../components/Icon";
import SmartTable from "../components/SmartTable";
import NotificationPanel from "../components/NotificationPanel";
import RestrictedOverview from "../components/dashboard/RestrictedOverview";
import { suppliersApi } from "../API/suppliers";
import { wholesaleApi } from "../API/wholesale";
import { extractErrorMessage } from "../API/client";
import { useAuth } from "../context/AuthContext";
import AddTeamMemberModal from "../components/team/AddTeamMemberModal";

const money = n => new Intl.NumberFormat("en-RW").format(Number(n) || 0) + " RWF";
const date = v => v ? new Date(v).toLocaleDateString("en-GB") : "—";

function Header({ eyebrow, title, description }) { return <div className="dash-page-head"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div></div>; }
function Metric({ icon, label, value, sub }) { return <div className="metric"><div className="metric-icon"><Icon name={icon}/></div><div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div></div>; }
function Remote({ load, children, deps = [] }) {
  const [state, setState] = useState({ loading: true, data: null, error: "" });
  useEffect(() => { let live = true; const refresh = () => load().then(data => live && setState({ loading: false, data, error: "" })).catch(error => live && setState({ loading: false, data: null, error: extractErrorMessage(error) })); setState({ loading: true, data: null, error: "" }); refresh(); const timer = window.setInterval(refresh, 30000); return () => { live = false; window.clearInterval(timer); }; }, deps);
  if (state.loading) return <div className="empty-state"><h3>Loading live supplier data…</h3></div>;
  if (state.error) return <div className="form-error">{state.error}</div>;
  return children(state.data);
}

function Overview() { const { user } = useAuth(); const restricted = user?.isOnboarded === false; if (restricted) return <><Header eyebrow="SUPPLIER PLATFORM" title="Supplier dashboard" description="Complete onboarding to unlock live supplier operations."/><div className="metric-grid"><Metric icon="box" label="Wholesale products" value="—" sub="Available after onboarding"/><Metric icon="cart" label="Vendor orders" value="—" sub="Available after onboarding"/><Metric icon="chart" label="Sales" value="—" sub="Available after onboarding"/><Metric icon="wallet" label="Protected funds" value="—" sub="Available after onboarding"/></div></>; return <Remote load={async () => { const [finance, products, delivery] = await Promise.all([suppliersApi.getFinanceSummary(), suppliersApi.getMyProducts(), suppliersApi.getDeliverySummary()]); return { finance: finance.summary || {}, products: products.products || [], delivery: delivery.summary || {} }; }}>
  {({ finance, products, delivery }) => <><Header eyebrow="SUPPLIER PLATFORM" title="Supplier dashboard" description="Overview of your supplier account and marketplace activity."/><div className="metric-grid"><Metric icon="box" label="Wholesale products" value={products.length} sub="Active catalog"/><Metric icon="cart" label="Vendor orders" value={Number(delivery.activeShipments || 0) + Number(delivery.deliveredThisMonth || 0)} sub="Current activity"/><Metric icon="chart" label="Sales" value={money(finance.grossSales)} sub="Total wholesale sales"/><Metric icon="wallet" label="Protected funds" value={money(finance.escrowHeld)} sub="Funds currently held"/></div><div className="verified-box"><b>Supplier account overview</b><p>Track products, vendor orders, sales, and protected settlements from this dashboard.</p></div></>}
</Remote>; }

function ProductForm({ value, onCancel, onSave }) { const [form, setForm] = useState(value); const update = e => setForm({ ...form, [e.target.name]: e.target.value }); return <div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={onCancel}>×</button><h2>{value._id ? "Edit" : "Add"} wholesale product</h2>{["name", "category", "unit", "wholesalePrice", "retailPrice", "moq", "stockQuantity", "bulkDiscount", "shortDescription"].map(key => <label className="field" key={key}><span>{key.replace(/([A-Z])/g, " $1")}</span>{key === "shortDescription" ? <textarea name={key} value={form[key] || ""} onChange={update}/> : <input name={key} type={["wholesalePrice", "retailPrice", "moq", "stockQuantity", "bulkDiscount"].includes(key) ? "number" : "text"} value={form[key] ?? ""} onChange={update} required={key === "name" || key === "wholesalePrice"}/>}</label>)}<div className="modal-actions"><button className="outline-btn" onClick={onCancel}>Cancel</button><button className="gradient-btn" onClick={() => onSave(form)}>Save</button></div></div></div>; }

function ProductTable({ products }) {
  const [edit, setEdit] = useState(null);
  const [rows, setRows] = useState(products);
  const [notice, setNotice] = useState("");
  useEffect(() => setRows(products), [products]);
  const save = async value => { try { const result = value._id ? await suppliersApi.updateProduct(value._id, value) : await suppliersApi.createProduct(value); setRows(current => value._id ? current.map(row => row._id === value._id ? result.product : row) : [result.product, ...current]); setEdit(null); } catch (error) { setNotice(extractErrorMessage(error)); } };
  const remove = async row => { try { await suppliersApi.deleteProduct(row._id); setRows(current => current.filter(item => item._id !== row._id)); } catch (error) { setNotice(extractErrorMessage(error)); } };
  return <><Header eyebrow="SUPPLIER PLATFORM" title="Wholesale products" description="Manage products stored in the supplier catalog."/><button className="gradient-btn" onClick={() => setEdit({ name: "", category: "General", unit: "piece", wholesalePrice: 0, moq: 1, stockQuantity: 0, bulkDiscount: 0, shortDescription: "" })}><Icon name="plus"/> Add wholesale product</button>{notice && <div className="form-error">{notice}</div>}<div className="data-card"><SmartTable columns={[{ key: "name", label: "Product" }, { key: "category", label: "Category" }, { key: "wholesalePrice", label: "Wholesale price", render: r => money(r.wholesalePrice) }, { key: "stockQuantity", label: "Stock" }, { key: "status", label: "Status" }]} rows={rows} rowKey={r => r._id} searchPlaceholder="Search wholesale products…" empty="No wholesale products in the database." actions={r => <><button onClick={() => setEdit(r)} title="Edit"><Icon name="edit"/></button><button onClick={() => remove(r)} title="Delete"><Icon name="trash"/></button></>}/></div>{edit && <ProductForm value={edit} onCancel={() => setEdit(null)} onSave={save}/>}</>;
}
function Products() { return <Remote load={suppliersApi.getMyProducts}>{({ products = [] }) => <ProductTable products={products}/>}</Remote>; }

function Orders() { return <Remote load={wholesaleApi.getMine}>{data => <><Header eyebrow="B2B ORDERS" title="Vendor orders" description="Wholesale orders stored for this supplier account."/><div className="data-card"><SmartTable columns={[{ key: "orderNumber", label: "Order" }, { key: "vendor", label: "Vendor", render: r => r.vendor?.companyName || r.vendor?.Fullname || "Vendor" }, { key: "totalAmount", label: "Total", render: r => money(r.totalAmount) }, { key: "status", label: "Status" }, { key: "createdAt", label: "Created", render: r => date(r.createdAt) }]} rows={data.orders || []} rowKey={r => r._id} searchPlaceholder="Search vendor orders…" empty="No wholesale orders in the database."/></div></>}</Remote>; }
function Inventory() { return <Remote load={suppliersApi.getMyProducts}>{({ products = [] }) => <><Header eyebrow="INVENTORY" title="Inventory" description="Stock quantities from supplier product records."/><div className="metric-grid"><Metric icon="box" label="Stock units" value={products.reduce((sum, p) => sum + Number(p.stockQuantity || 0), 0)} sub="Across database products"/><Metric icon="grid" label="Low stock" value={products.filter(p => Number(p.stockQuantity || 0) < 10).length} sub="Below 10 units"/><Metric icon="cart" label="Catalog items" value={products.length} sub="Supplier products"/></div><div className="data-card"><SmartTable columns={[{ key: "name", label: "Product" }, { key: "stockQuantity", label: "Available" }, { key: "moq", label: "MOQ" }, { key: "status", label: "Status" }]} rows={products} rowKey={r => r._id} searchPlaceholder="Search inventory…" empty="No inventory records in the database."/></div></>}</Remote>; }
function Analytics() { const [range, setRange] = useState("30d"); return <Remote load={() => suppliersApi.getAnalytics({ range })} deps={[range]}>{({ analytics = {} }) => <><Header eyebrow="ANALYTICS" title="Analytics" description="Wholesale performance calculated from stored orders."/><select className="period-select" value={range} onChange={e => setRange(e.target.value)}><option value="30d">30 days</option><option value="3m">3 months</option><option value="1y">1 year</option></select><div className="metric-grid"><Metric icon="chart" label="Sales" value={money(analytics.grossSales)} sub={`${analytics.orderCount || 0} database orders`}/><Metric icon="cart" label="Units sold" value={analytics.unitsSold || 0} sub="Recorded order items"/><Metric icon="users" label="Average order" value={money(analytics.averageOrderValue)} sub="Calculated from orders"/></div><div className="data-card"><SmartTable columns={[{ key: "name", label: "Product" }, { key: "units", label: "Units" }, { key: "revenue", label: "Revenue", render: r => money(r.revenue) }]} rows={analytics.topProducts || []} rowKey={r => r.name} searchPlaceholder="Search product performance…" empty="No analytics records for this period."/></div></>}</Remote>; }
function Payments() { return <Remote load={async () => { const [summary, payouts] = await Promise.all([suppliersApi.getFinanceSummary(), suppliersApi.getPayouts()]); return { summary: summary.summary || {}, payouts: payouts.payouts || [] }; }}>{({ summary, payouts }) => <><Header eyebrow="PAYMENTS" title="Payments" description="Supplier wallet and payout records from the database."/><div className="metric-grid"><Metric icon="wallet" label="Available payout" value={money(summary.availablePayout)} sub="Wallet balance"/><Metric icon="chart" label="Pending payouts" value={money(summary.pendingPayouts)} sub="Pending database records"/><Metric icon="box" label="Released this period" value={money(summary.releasedThisPeriod)} sub="Recorded settlements"/></div><div className="data-card"><SmartTable columns={[{ key: "_id", label: "Reference" }, { key: "amount", label: "Amount", render: r => money(r.amount) }, { key: "method", label: "Method" }, { key: "status", label: "Status" }, { key: "requestedAt", label: "Requested", render: r => date(r.requestedAt) }]} rows={payouts} rowKey={r => r._id} searchPlaceholder="Search payouts…" empty="No payout records in the database."/></div></>}</Remote>; }
function Reports() { return <Remote load={async () => { const [summary, analytics, ledger] = await Promise.all([suppliersApi.getFinanceSummary(), suppliersApi.getAnalytics({ range: "30d" }), suppliersApi.getFinanceLedger()]); return { summary: summary.summary || {}, analytics: analytics.analytics || {}, ledger: ledger.entries || [] }; }}>{({ summary, analytics, ledger }) => <><Header eyebrow="REPORTS" title="Reports" description="Reports generated from supplier financial and order records."/><div className="data-card"><SmartTable columns={[{ key: "description", label: "Record" }, { key: "kind", label: "Type" }, { key: "amount", label: "Amount", render: r => money(r.amount) }, { key: "at", label: "Date", render: r => date(r.at) }]} rows={ledger} rowKey={r => r._id} searchPlaceholder="Search report records…" empty="No report records in the database."/><p className="tiny">30 day sales: {money(analytics.grossSales)} · Total recorded sales: {money(summary.grossSales)}</p></div></>}</Remote>; }
function Team() { const [members,setMembers]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [editing,setEditing]=useState(null); const load=()=>{setLoading(true);return suppliersApi.getTeam().then(data=>setMembers(data.members||[])).catch(e=>setError(extractErrorMessage(e))).finally(()=>setLoading(false));}; useEffect(()=>{load();},[]); const save=async form=>{setError(""); const payload={fullName:form.name,phone:form.phone,email:form.email,password:form.password,role:form.role}; if(form.id){await suppliersApi.updateTeamMember(form.id,{...payload,status:form.status});setNotice("Team member updated.");}else{await suppliersApi.addTeamMember(payload);setNotice("Team member added.");}setEditing(null);await load();}; const remove=async row=>{if(!window.confirm(`Remove ${row.fullName||"this team member"}?`))return;try{await suppliersApi.removeTeamMember(row._id);setNotice("Team member removed.");await load();}catch(e){setError(extractErrorMessage(e));}}; return <><div className="dash-page-head"><div><span className="eyebrow">TEAM / STAFF</span><h1>Team & staff</h1><p>Live supplier team records from the database.</p></div><button className="gradient-btn" onClick={()=>setEditing({})}><Icon name="plus"/> Add team member</button></div>{notice&&<div className="form-alert success">{notice}</div>}{error&&<div className="form-error">{error}</div>}<div className="data-card">{loading?<div className="empty-state"><h3>Loading team…</h3></div>:<SmartTable columns={[{ key: "fullName", label: "Member" }, { key: "role", label: "Role" }, { key: "phone", label: "Phone" }, { key: "status", label: "Status" }]} rows={members} rowKey={r => r._id} searchPlaceholder="Search team…" empty="No team members in the database." actions={row=>row.role!=="OWNER"&&<><button className="table-action-btn" onClick={()=>setEditing(row)}>Edit</button><button className="table-action-btn" onClick={()=>remove(row)}>Remove</button></>}/>}</div>{editing&&<AddTeamMemberModal mode="supplier" value={editing} onCancel={()=>setEditing(null)} onSave={save}/>}</>; }
function Settings() { const [form, setForm] = useState(null); const [notice, setNotice] = useState(""); return <Remote load={async () => { const result = await suppliersApi.getMyProfile(); return result.supplier || result; }}>{profile => { if (!form) setForm({ businessName: profile.businessName || "", phone: profile.phone || "", email: profile.email || "", description: profile.description || "" }); if (!form) return <div className="empty-state"><h3>Loading profile…</h3></div>; const save = async () => { try { await suppliersApi.updateMyProfile(form); setNotice("Profile saved to the database."); } catch (error) { setNotice(extractErrorMessage(error)); } }; return <><Header eyebrow="SETTINGS" title="Supplier profile" description="Edit the supplier profile stored in the database."/><div className="data-card">{notice && <p className="success-text">{notice}</p>}{["businessName", "phone", "email"].map(key => <label className="field" key={key}><span>{key.replace(/([A-Z])/g, " $1")}</span><input value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })}/></label>)}<label className="field"><span>Description</span><textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })}/></label><button className="gradient-btn" onClick={save}>Save changes</button></div></>; }}</Remote>; }

export default function SupplierDashboard() { const path = useLocation().pathname; let page = <Overview/>; if (path.includes("/products")) page = <Products/>; else if (path.includes("/orders")) page = <Orders/>; else if (path.includes("/inventory")) page = <Inventory/>; else if (path.includes("/analytics")) page = <Analytics/>; else if (path.includes("/payments")) page = <Payments/>; else if (path.includes("/reports")) page = <Reports/>; else if (path.includes("/team")) page = <Team/>; else if (path.includes("/notifications")) page = <NotificationPanel/>; else if (path.includes("/settings")) page = <Settings/>; return <DashboardLayout><RestrictedOverview>{page}</RestrictedOverview></DashboardLayout>; }
