import { client } from "./client";

export const suppliersApi = {
  getAll: (params) =>
    client.get("/suppliers", { params }).then((r) => r.data),
  getByIdOrSlug: (idOrSlug) =>
    client.get(`/suppliers/${idOrSlug}`).then((r) => r.data),
  getProducts: (id) =>
    client.get(`/suppliers/${id}/products`).then((r) => r.data),
  onboard: (payload) =>
    client.post("/suppliers/onboard", payload).then((r) => r.data),
  getMyProfile: () =>
    client.get("/suppliers/me/profile").then((r) => r.data),
  updateMyProfile: (payload) =>
    client.patch("/suppliers/me/profile", payload).then((r) => r.data),
  getMyProducts: () =>
    client.get("/suppliers/me/products").then((r) => r.data),
  createProduct: (payload) =>
    client.post("/suppliers/me/products", payload).then((r) => r.data),
  updateProduct: (id, payload) =>
    client.put(`/suppliers/me/products/${id}`, payload).then((r) => r.data),
  deleteProduct: (id) =>
    client.delete(`/suppliers/me/products/${id}`).then((r) => r.data),
  getFinanceSummary: () =>
    client.get("/suppliers/me/finance/summary").then((r) => r.data),
  getFinanceLedger: (params) =>
    client.get("/suppliers/me/finance/ledger", { params }).then((r) => r.data),
  getPayouts: (params) =>
    client.get("/suppliers/me/finance/payouts", { params }).then((r) => r.data),
  getAnalytics: (params) =>
    client.get("/suppliers/me/finance/analytics", { params }).then((r) => r.data),
  getDeliverySummary: () =>
    client.get("/suppliers/me/delivery/summary").then((r) => r.data),
  getSupplyRequests: (params) =>
    client.get("/suppliers/me/supply-requests", { params }).then((r) => r.data),
  getTeam: () =>
    client.get("/suppliers/me/team").then((r) => r.data),
  addTeamMember: (payload) =>
    client.post("/suppliers/me/team", payload).then((r) => r.data),
  updateTeamMember: (id, payload) =>
    client.patch(`/suppliers/me/team/${id}`, payload).then((r) => r.data),
  removeTeamMember: (id) =>
    client.delete(`/suppliers/me/team/${id}`).then((r) => r.data),
  getReviews: (params) =>
    client.get("/suppliers/me/reviews", { params }).then((r) => r.data),
};
